### ISSUE TITLE
td_agent_gem provider broken

### ISSUE THREAD

**Issue by Raboo** [treasure-data/chef-td-agent#23]
Hi,

The td_agent_gem provider seems to not work as intended.
Adding this to a recipe causes an failure.

```
td_agent_gem "tail-multiline" do
  plugin true
end
```

It seems like it is not able to take the name inside the td_agent_gem and assign it to the package_name variable.
I'm running chef 10 if it helps..

```
[Tue, 10 Jun 2014 16:36:08 +0200] INFO: Processing td-agent_gem[tail-multiline] action install (dp_td-agent_wrapper::default line 39)

================================================================================
Error executing action `install` on resource 'td-agent_gem[tail-multiline]'
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Required argument package_name is missing!

Cookbook Trace:
---------------
/var/cache/chef/cookbooks/td-agent/libraries/provider_td_rubygems.rb:31:in `initialize'

Resource Declaration:
---------------------
# In /var/cache/chef/cookbooks/dp_td-agent_wrapper/recipes/default.rb

 40: td_agent_gem "tail-multiline" do
 41:   plugin true
 42: end
 43:

Compiled Resource:
------------------
# Declared in /var/cache/chef/cookbooks/dp_td-agent_wrapper/recipes/default.rb:40:in `from_file'

td_agent_gem("tail-multiline") do
  cookbook_name "dp_td-agent_wrapper"
  provider Chef::Provider::Package::TdRubygems
  action :install
  retry_delay 2
  plugin true
  recipe_name "default"
  retries 0
end

[Tue, 10 Jun 2014 16:36:08 +0200] ERROR: Running exception handlers
[Tue, 10 Jun 2014 16:36:10 +0200] FATAL: Saving node information to /var/cache/chef/failed-run-data.json
[Tue, 10 Jun 2014 16:36:10 +0200] ERROR: Exception handlers complete
[Tue, 10 Jun 2014 16:36:10 +0200] FATAL: Stacktrace dumped to /var/cache/chef/chef-stacktrace.out
[Tue, 10 Jun 2014 16:36:10 +0200] FATAL: Chef::Exceptions::ValidationFailed: td-agent_gem[tail-multiline] (dp_td-agent_wrapper::default line 40) had an error: Chef::Exceptions::ValidationFailed: Required argument package_name is missing!
```

**Comment by Raboo** [comment]
hmm, not running chef v10 since long ago and this ticket is stale, closing.
